task 1:

In [46]:
import numpy as np
a = np.random.random((10,3))
print(a)

[[0.39406733 0.44819306 0.64808112]
 [0.48612645 0.33766975 0.59409383]
 [0.45278263 0.22286605 0.49076879]
 [0.07501452 0.84952618 0.21623807]
 [0.07755718 0.58806054 0.80368509]
 [0.98699986 0.66254065 0.49056118]
 [0.45789855 0.5241552  0.25975133]
 [0.12132639 0.40394456 0.10442887]
 [0.39315525 0.44541354 0.99005181]
 [0.88209352 0.02371661 0.36217542]]


In [47]:
for i in range(0, 10):
    near = a[i][0]
    for j in range(0,3):
        c = (0.5 - a[i][j]) 
        c = abs(c)
        if (c) < (0.5 - near):
            near = a[i][j]
    print ("nearest to 0.5 in ", i, "string is ", near)

nearest to 0.5 in  0 string is  0.44819305572113577
nearest to 0.5 in  1 string is  0.4861264515478061
nearest to 0.5 in  2 string is  0.49076879094791004
nearest to 0.5 in  3 string is  0.8495261837215615
nearest to 0.5 in  4 string is  0.5880605358702152
nearest to 0.5 in  5 string is  0.9869998561535946
nearest to 0.5 in  6 string is  0.5241552022841478
nearest to 0.5 in  7 string is  0.40394455640872995
nearest to 0.5 in  8 string is  0.4454135389360365
nearest to 0.5 in  9 string is  0.882093516120649


task 2:

In [48]:
import numpy as np
arr = np.random.random((6,6))
print(arr)

[[0.82857776 0.88848491 0.82049496 0.23692362 0.31762892 0.61397163]
 [0.08389844 0.71777771 0.64269023 0.02733732 0.69097688 0.33193552]
 [0.23222989 0.12544787 0.23874152 0.51314132 0.78530033 0.70536533]
 [0.01914153 0.13470816 0.01912815 0.27736796 0.01026869 0.25619182]
 [0.09832231 0.83266395 0.29774309 0.72883645 0.36744668 0.94904616]
 [0.31073274 0.37948263 0.25067146 0.29690348 0.00612601 0.44296004]]


In [54]:
for i in range(0,6):
    s = 0
    for j in range(0,6):
        s += arr[i][j]
    minn = arr[0][i]
    for k in range(1,6):
        if arr[k][i] < minn:
            minn = arr[k][i]
        b = s / minn
    print("result for", i,"is", b)

result for 0 is 193.61469414399264
result for 1 is 19.885678998941227
result for 2 is 135.93716215699024
result for 3 is 26.220800992726033
result for 4 is 534.4519867217992
result for 5 is 6.58442716128313


task 3:

In [55]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
maxx = 0
for i in range(0, 8):
    if (x[i] == 0):
        if (x[i+1] > maxx):
            maxx = x[i+1]
print("max after 0 is", maxx)

max after 0 is 5


In [60]:
import numpy as np
y = np.ones(10)
p = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(0,8):
    y[p[j]] += 1
print(y)


[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
