task 1:

In [3]:
import numpy as np
a = np.floor(10 * np.random.rand(10,3) - 5)
print (a)

[[-2.  1. -4.]
 [ 2.  2. -1.]
 [-1. -3. -2.]
 [-2. -3. -4.]
 [ 4.  0.  4.]
 [ 2. -1. -1.]
 [-1. -4.  3.]
 [-3.  1.  1.]
 [-2.  1. -4.]
 [-5.  3.  2.]]


In [10]:
print ("nearest to 0.5:")
print(np.array([a[lines][np.argsort(np.abs(a[lines] - 0.5))[0]] for lines in range(10)]))

nearest to 0.5:
[ 1.  2. -1. -2.  0.  2. -1.  1.  1.  2.]


task 2:

In [5]:
b = np.floor(10 * np.random.rand(6,6) + 1)
print (b)

[[ 2.  8. 10.  5.  6.  1.]
 [ 5.  3. 10.  6.  3. 10.]
 [ 7.  2.  3.  8.  1.  1.]
 [ 5.  3.  7.  8.  1. 10.]
 [ 4. 10.  2.  4.  9.  5.]
 [ 5.  5.  9.  6.  4.  2.]]


In [11]:
print("sum str / min el st:")
print(np.array([np.sum(b[lines]) / np.min(b.transpose()[lines]) for lines in range(6)]))

sum str / min el st:
[16.  18.5 11.   8.5 34.  31. ]


task 3:

In [7]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(x)

[6 2 0 3 0 0 5 7 0]


In [14]:
print("max after 0:")
print(np.max(np.array([(int)(x[i] == 0) * x[i+1] for i in range(len(x) - 1)])))

max after 0:
5


task 4:

In [16]:
y = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
print(y)
print(i)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 5 5 5 8]


In [18]:
print(np.array([y[j] + len(i[i == j]) for j in range(10)]))

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
